### ISSUE TITLE
Migration project organization.

### ISSUE THREAD

**Issue by cweijan** [mark-wiemer/ahkpp#359]
Hi @mark-wiemer, I have not continued to maintain autohotkey-plus for a long time, I plan to delete the [vscode-autohotkey ](https://github.com/vscode-autohotkey)organization, please migrate your project from this organization.

**Comment by mark-wiemer** [comment]
Are you OK deprecating your extension in favor of mine?

**Comment by mark-wiemer** [comment]
Done.

**Comment by cweijan** [comment]
No, I don't maintain autohotkey-plus anymore, but I still use it, ahk++ it makes some changes to the original functions, such as formatting, so I don't use it.

**Comment by mark-wiemer** [comment]
You can still use deprecated extensions. I think people considering your extension should know that it's not maintained. Maybe update the readme with a depreciation notice at least?
